### ISSUE TITLE
dispenser with flint and steel in it can not light the portal

### ISSUE THREAD

**Issue by 755437985** [Darkhax-Minecraft/Hunting-Dimension#19]
I was trying to light the portal with a dispenser but failed.
Only fires appeared on the frame block and no portal blocks generated.

**Comment by KelleyEngineering** [comment]
you light the portal with a sword, not flint and steel

**Comment by 755437985** [comment]
I do can light the portal with a flint and steel manually.
The matter is that I cannot light it with a dispenser.

**Comment by Darkhax** [comment]
Yes, this is because the flint and steel is what lights the portal, not the fire. The flint and steel may be removed as a lighting option in the future, I am not sure. I will give this some consideration.

**Comment by Darkhax** [comment]
This issue has been partially fixed. It only works when the fire block is created in a place where the fire can exist. So this limits you to positions on the bottom of the portal, and positions with a flammable block on the other side. This limitation is due to the vanilla portal creation code being hard coded, so I don't have the right timing.
