### ISSUE TITLE
No Stars / Sky doesn't look like night-time.

### ISSUE THREAD

**Issue by Salads** [Darkhax-Minecraft/Hunting-Dimension#29]
Mod Version: 1.0.24
Modpack: Sevtech Ages
Minecraft Version: 1.12.2

The sky is a weird bluish color, so while I can use Astral Sorcery's crafting table for easy starlight, I cannot do anything related to constellations in the dimension because the stars are not visible in the sky.

[Imgur of sky as it is now](https://i.imgur.com/aipkYL4.png)

[This might be the culprit in WorldProviderHunting.java](https://github.com/Darkhax-Minecraft/Hunting-Dimension/blob/273ebbbfc4c05d6a435fe5db39f72ced9318e5b7/src/main/java/net/darkhax/huntingdim/dimension/WorldProviderHunting.java#L72)

According to [this form thread](https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/modification-development/1422823-night-for-ever?comment=11) it should return 0.5 for a midnight starry sky.

**Comment by Darkhax** [comment]
This is in part intentional. In versions of the mod that are slightly newer than the one you used while reporting, the sky has been replaced with a thick green fog. The focus of the hunting dimension is building mob farms, and the astral sorcery stuff is just a minor benefit which makes server play with Astral Sorcery a bit easier. 

I can add this as a configuration option, however it's going to be a bit of work. The issue is slightly bigger than what you described, while setting the angle to 0.5f is part of it, the isSurfaceWorld method must also return true. This method is used by things like compasses, clocks, and some modded world gen.

**Comment by Salads** [comment]
I think I can understand that.

I suppose even if it were to be made 0.5, the constellations in Astral Sorcery wouldn't change at which point it might be not worth the work to specifically add that much compatability to some completely separate mod, and it's still useful for liquid starlight generation since it's still technically "night time".

Feel free to close :)

**Comment by Darkhax** [comment]
Unfortunately, I really like how the dimension looks with stars so I pushed a new release of the mod which sets it to be a surface world. If you think about it, it makes sense that things like the clock would show midnight instead of just spinning around, and being able to use a compass isn't extremely game breaking. If any issues come from this change I will fix them, or work on a render rewrite to show the stars.
