### ISSUE TITLE
World Generation

### ISSUE THREAD

**Issue by Cazadorsniper** [Darkhax-Minecraft/Hunting-Dimension#4]
1. Is it possible for the dimension to generate a non-void terrain when using a world type like Garden of Glass?

2. Is it "heightScale": 684.412, that controls the height of the terrain? (want to make the dimension completely flat)

**Comment by Darkhax** [comment]
Hello

The world generator currently makes use of the surface generator, so it will mimic the behavior including most mods that change the surface dimension. I am planning to replace that code with completely custom generator code within the next day or two which should fix this issue. I suspect Garden of Glass would have a config file to change how things work based on the dimension id. 

The json file generated by the mod is based on the vanilla world settings. If you've ever looked at the world customization options when creating a new world in vanilla, you may notice some of these options. The heightScale is used when the game calculates how high to stretch hills, so adjusting this number should help you achieve the goal of flatter terrain. You can find coverage of all the options [here](https://gaming.stackexchange.com/questions/165826/how-do-the-customized-world-settings-work)

**Comment by Cazadorsniper** [comment]
Garden of Glass has no config file I know of and thanks.

**Comment by Darkhax** [comment]
Oh I see. I am not super familiar with how that mod works, and it's not open source so I can't look into the code or make a PR for this. Do you need to use Garden of Glass specifically, or would [YUNoMakeGoodMap](https://minecraft.curseforge.com/projects/yunomakegoodmap) work? Also, do you know if the mining dimension is affected by garden of glass? If not, I am pretty confident I can fix it on my end.

**Comment by Cazadorsniper** [comment]
mining dimension is not affected by Garden of Glass.

Yes, need Garden of Glass specifically because I only want the overworld as void nothing else and it doesn't affect other world types.

**Comment by Darkhax** [comment]
Thanks for bringing up these questions. I think they've helped me make a good choice that fixes a few bugs related to worldgen and makes the mod more usable overall. I've made 3 feature changes related to your issue, that should help you add this mod and customize it the way you want.

1. Instead of using the same world type (super flat, amplified, ect) as the surface world, it will now default to the default/normal world generator. This should fix the issue you were having with the dimension being empty. If you want to revert this behaviour, there is a config option called `mimicSurfaceWorld` which can be set to true to revert.
2. The world type used by the dimension can now be configured to a specific world type by changing the `worldType` config option. So if you want the dimension to be flat you can set this to flat and it will act like it's a super flat world. 
3. The default biome for the dimension is the plains biome. This update makes it configurable, so you can change the default/base biome to use by changing the `initialBiome` option. 

Hope these changes have made the mod easier for you to use :)

Edit: The new version is now live on [curse](https://minecraft.curseforge.com/projects/hunting-dimension/files/2511538).

**Comment by Cazadorsniper** [comment]
Thank You
